#lang racket
(require rackunit "callsign-generate.rkt")

; digit?
(check-false (digit? #\A))
(check-false (digit? #\B))
(check-false (digit? #\C))
(check-false (digit? #\D))
(check-false (digit? #\E))
(check-false (digit? #\F))
(check-false (digit? #\G))
(check-false (digit? #\H))
(check-false (digit? #\I))
(check-false (digit? #\J))
(check-false (digit? #\K))
(check-false (digit? #\L))
(check-false (digit? #\M))
(check-false (digit? #\N))
(check-false (digit? #\O))
(check-false (digit? #\P))
(check-false (digit? #\Q))
(check-false (digit? #\R))
(check-false (digit? #\S))
(check-false (digit? #\T))
(check-false (digit? #\U))
(check-false (digit? #\V))
(check-false (digit? #\W))
(check-false (digit? #\X))
(check-false (digit? #\Y))
(check-false (digit? #\Z))
(check-false (digit? #\a))
(check-false (digit? #\b))
(check-false (digit? #\c))
(check-false (digit? #\d))
(check-false (digit? #\e))
(check-false (digit? #\f))
(check-false (digit? #\g))
(check-false (digit? #\h))
(check-false (digit? #\i))
(check-false (digit? #\j))
(check-false (digit? #\k))
(check-false (digit? #\l))
(check-false (digit? #\m))
(check-false (digit? #\n))
(check-false (digit? #\o))
(check-false (digit? #\p))
(check-false (digit? #\q))
(check-false (digit? #\r))
(check-false (digit? #\s))
(check-false (digit? #\t))
(check-false (digit? #\u))
(check-false (digit? #\v))
(check-false (digit? #\w))
(check-false (digit? #\x))
(check-false (digit? #\y))
(check-false (digit? #\z))
(check-true (digit? #\0))
(check-true (digit? #\1))
(check-true (digit? #\2))
(check-true (digit? #\3))
(check-true (digit? #\4))
(check-true (digit? #\5))
(check-true (digit? #\6))
(check-true (digit? #\7))
(check-true (digit? #\8))
(check-true (digit? #\9))
(check-false (digit? #\!))
(check-false (digit? #\#))
(check-false (digit? #\@))
(check-false (digit? #\_))
(check-false (digit? 'BT#))
(check-false (digit? 'SK@))
(check-false (digit? 'AR!))
(check-false (digit? '(#\A #\B #\C)))
(check-false (digit? '(#\1 #\2 #\3)))
(check-false (digit? '(1 2 3)))
(check-false (digit? '(A B C)))
(check-false (digit? '(A (B C))))
(check-false (digit? '()))

; digits-from
(check-equal? (digits-from '(#\A #\B #\C #\1 #\2 #\3)) '(#\1 #\2 #\3))
(check-equal? (digits-from '(#\A #\1 #\B #\2 #\C #\3)) '(#\1 #\2 #\3))
(check-equal? (digits-from '(A #\A #\9 Q #\B #\8 #\C M #\4)) '(#\9 #\8 #\4))
(check-equal? (digits-from '()) '())
(check-equal? (digits-from '(#\A #\B #\C)) '())

; letter?
(check-true (letter? #\A))
(check-true (letter? #\B))
(check-true (letter? #\C))
(check-true (letter? #\D))
(check-true (letter? #\E))
(check-true (letter? #\F))
(check-true (letter? #\G))
(check-true (letter? #\H))
(check-true (letter? #\I))
(check-true (letter? #\J))
(check-true (letter? #\K))
(check-true (letter? #\L))
(check-true (letter? #\M))
(check-true (letter? #\N))
(check-true (letter? #\O))
(check-true (letter? #\P))
(check-true (letter? #\Q))
(check-true (letter? #\R))
(check-true (letter? #\S))
(check-true (letter? #\T))
(check-true (letter? #\U))
(check-true (letter? #\V))
(check-true (letter? #\W))
(check-true (letter? #\X))
(check-true (letter? #\Y))
(check-true (letter? #\Z))
(check-true (letter? #\a))
(check-true (letter? #\b))
(check-true (letter? #\c))
(check-true (letter? #\d))
(check-true (letter? #\e))
(check-true (letter? #\f))
(check-true (letter? #\g))
(check-true (letter? #\h))
(check-true (letter? #\i))
(check-true (letter? #\j))
(check-true (letter? #\k))
(check-true (letter? #\l))
(check-true (letter? #\m))
(check-true (letter? #\n))
(check-true (letter? #\o))
(check-true (letter? #\p))
(check-true (letter? #\q))
(check-true (letter? #\r))
(check-true (letter? #\s))
(check-true (letter? #\t))
(check-true (letter? #\u))
(check-true (letter? #\v))
(check-true (letter? #\w))
(check-true (letter? #\x))
(check-true (letter? #\y))
(check-true (letter? #\z))
(check-false (letter? #\0))
(check-false (letter? #\1))
(check-false (letter? #\2))
(check-false (letter? #\3))
(check-false (letter? #\4))
(check-false (letter? #\5))
(check-false (letter? #\6))
(check-false (letter? #\7))
(check-false (letter? #\8))
(check-false (letter? #\9))
(check-false (letter? #\!))
(check-false (letter? #\#))
(check-false (letter? #\@))
(check-false (letter? #\_))
(check-false (letter? 'BT#))
(check-false (letter? 'SK@))
(check-false (letter? 'AR!))
(check-false (letter? '(#\A #\B #\C)))
(check-false (letter? '(#\1 #\2 #\3)))
(check-false (letter? '(1 2 3)))
(check-false (letter? '(A B C)))
(check-false (letter? '(A (B C))))
(check-false (letter? '()))

; letters-from
(check-equal? (letters-from '(#\A #\B #\C #\1 #\2 #\3)) '(#\A #\B #\C))
(check-equal? (letters-from '(#\Q #\1 #\S #\2 #\O #\3)) '(#\Q #\S #\O))
(check-equal? (letters-from '(A #\A #\9 Q #\B #\8 #\C M #\4)) '(#\A #\B #\C))
(check-equal? (letters-from '()) '())
(check-equal? (letters-from '(#\1 #\2 #\3)) '())
